resources:
  - name: dwpdigital-kafka-queue-trawler
    type: registry-image-resource
    source:
      repository: dwpdigital/kafka-queue-trawler
    check_every: 5m

  - name: ecr-dwpdigital-kafka-queue-trawler-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "kafka-queue-trawler"

  - name: ecr-dwpdigital-kafka-queue-trawler
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "kafka-queue-trawler"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-kafka-queue-trawler-dev
    serial_groups: [kafka-queue-trawler]
    plan:
      - get: dwpdigital-kafka-queue-trawler
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-kafka-queue-trawler-dev
        params:
          image: "dwpdigital-kafka-queue-trawler/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-kafka-queue-trawler
    serial_groups: [kafka-queue-trawler]
    plan:
      - get: dwpdigital-kafka-queue-trawler
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-kafka-queue-trawler
        params:
          image: "dwpdigital-kafka-queue-trawler/image.tar"
        attempts: 3
