jobs:
  - name: kafka-queue-trawler-pr
    plan:
      - get: kafka-queue-trawler-pr
        trigger: true
        version: every
      - put: kafka-queue-trawler-pr
        params:
          path: kafka-queue-trawler-pr
          status: pending
        input_mapping:
          kafka-queue-trawler: kafka-queue-trawler-pr
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          kafka-queue-trawler: kafka-queue-trawler-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          kafka-queue-trawler: kafka-queue-trawler-pr
        params:
          TF_WORKSPACE: "management-dev"
          DETAILED_EXITCODE: ""
        on_failure:
          put: kafka-queue-trawler-pr
          params:
            path: kafka-queue-trawler-pr
            status: failure
        on_success:
          put: kafka-queue-trawler-pr
          params:
            path: kafka-queue-trawler-pr
            status: success
